# Generated by Django 5.0.6 on 2024-07-02 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_photoitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photoitem',
            name='photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo_items', to='api.photo'),
        ),
    ]
